
# Project information
site_name: Ruby Changelog
site_url: https://rubychangelog.com/
site_author: Marek Kowalcze
site_description: >-
  Welcome to the RubyChangelog.com site! You can find here the history of Ruby programming language versions

# Repository
repo_name: kowal/ruby-changelog
repo_url: https://github.com/kowal/ruby-changelog

# Copyright
copyright: Copyright &copy; 2020-2021 Marek Kowalcze

# Configuration
theme:
  name: null
  logo: assets/favicon.ico
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
  palette:
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.ico

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kowal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kowal

extra_javascript:
  - https://cdn.jsdelivr.net/npm/evil-icons@1.9.0/assets/evil-icons.min.js
  - https://code.jquery.com/jquery-3.5.1.min.js
  - https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js
  - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js
  - https://www.gstatic.com/charts/loader.js
  - javascripts/charts-timeline.js

extra_css:
  - https://cdn.jsdelivr.net/npm/evil-icons@1.9.0/assets/evil-icons.min.css
  - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css
  - stylesheets/custom.css

# Page tree
nav:
  - Home: index.md
  - Versions:
    - Latest Versions: versions-latest.md
    - All Versions: versions-all.md
  - Other:
    - Ruby resources: links.md
